@startuml
class ToDoListApp {
    start()
}

class DataOps {
    ToDoList toDoList
    String currentPath
    getInstance()
    ToDoList readDataFile(String path)
    writeDataToFile(String path)
}

class ToDoController {
    newList()
    loadList()
    saveList()
    newListOnClick()
    loadListOnClick()
    saveListOnClick()
    newListOnClick()
    listSelectorOnClick()
}

class ToDoListListCell {
    updateItem(ListItem item, boolean empty)
}

class ToDoListListCellController {
    markComplete()
    editDetails()
    deleteItem()
    markCompleteOnClick()
    editDetailsOnClick()
    deleteItemOnClick()
}

class ToDoList {
    String title
    ArrayList<ListItem> items
    addItem(ListItem item)
}

class ListItem {
    String description
    String date
    boolean complete
}

ToDoList <-- ListItem
ToDoController <-- ToDoListListCell
ToDoListListCell <-- ToDoListListCellController
ToDoListApp <-- ToDoController
@enduml